### PR TITLE
Nothing in SoundCloud/Following #67

### PR DESCRIPTION
**Pull request by kriim**
This one fixes issue #67.

(Tested on Raspberry Pi 1 B)

### CODE REVIEW

**Comment by THS-on** [comment]
Thank you. It's working fine.

THS-on

**Comment by jjok** [comment]
It would be great to get a release with this fix in. Thanks.

**Comment by kh0p** [comment]
After applying this patch, running ncmpcpp and trying to get into 'Following':

```
what(): Malformed entity response line
Aborted (core dumped)
```

:question:

**Comment by jarpy** [comment]
As far as I can tell, this was [fixed](https://github.com/mopidy/mopidy-soundcloud/commit/faeb6710980f12b50b03bf78c1878be751b8e21a#diff-8a8a33548e097d35b2c8b147fb78d5f0L147) in #83.

Please reopen if I've missed something.

**Pull request closed without merging**
